### ISSUE TITLE
Formatting problem near the end of https://github.com/sudoplatform-labs/ffi-tutorials/blob/main/Wrapper_Data_Types/readme.md

### ISSUE THREAD

**Issue by mwherman2000** [sudoplatform-labs/ffi-tutorials#5]
Formatting problem near the end of https://github.com/sudoplatform-labs/ffi-tutorials/blob/main/Wrapper_Data_Types/readme.md

Thank you for putting these tutorials together.

**Comment by mccown** [comment]
@mwherman2000 thank you for catching this!  I had an extra "```" tag that threw everything off.  It should be fixed now.
